# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='visible',
            field=models.NullBooleanField(),
        ),
    ]
