# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 14:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160215_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.PollCategory'),
        ),
    ]
